name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply AKS Cluster
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform  # adjust if needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (Manual Approval)
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: terraform apply -auto-approve

      # Optional: add a step to verify cluster readiness or wait before next job
      # - name: Wait for AKS cluster readiness
      #   run: |
      #     # Add a script here to poll kube-api or just wait a few minutes

  # Separate job or separate workflow for Helm and Kubernetes manifests deployment:
  # This job runs after AKS is ready
  # helm_deploy:
  #   needs: terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - Checkout Code
  #     - Setup Kubectl and Helm (using azure/login or kubectl/helm setup actions)
  #     - Deploy Helm charts for ingress, cert-manager, etc.
