name: Deploy or Destroy AKS Cluster

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: Apply or Destroy AKS via Terraform Cloud
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform  # Adjust if .tf files are in another folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            terraform plan -out=tfplan
          else
            terraform plan -destroy -out=tfplan
          fi

      - name: Terraform Apply or Destroy
        run: terraform apply -auto-approve tfplan
