name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Plan and Apply AKS Cluster via Terraform Cloud
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform  # change if your .tf files are in another folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        run: terraform destroy -auto-approve tfplan
