name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Plan and Apply/Destroy AKS Cluster via Terraform Cloud
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform  # Change if your .tf files are in another folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # ---------- APPLY MODE ----------
      # Uncomment these 2 blocks when you want to create/update the AKS cluster

      # - name: Terraform Plan (Apply)
      #   run: terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan

      # ---------- DESTROY MODE ----------
      # Uncomment these 2 blocks when you want to destroy the AKS cluster

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan
