name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform plan AKS Cluster
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform  # adjust if needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Apply)
        run: terraform plan -apply

      - name: Terraform Apply
        run: terraform apply -auto-approve
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
